version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: changeguard-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: changeguard
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: changeguard-backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: changeguard-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
