import smtplib
from email.mime.text import MIMEText

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

SMTP_USERNAME = "vabsnanoti@gmail.com"
SMTP_PASSWORD = "oqtdievbzyuvbngw"

FROM_EMAIL = "changegard-bot@gmail.com"
TO_EMAIL = "vabsnanoti@gmail.com"


def send_email(change_id, risk_level, recommendation):

    subject = f"ChangeGuard AI - {change_id} - {risk_level}"

    body = f"""
Change Risk Analysis Completed

Change ID: {change_id}
Risk Level: {risk_level}
Recommendation: {recommendation}

Generated By: ChangeGuard AI
"""

    message = MIMEText(body)
    message["Subject"] = subject
    message["From"] = FROM_EMAIL
    message["To"] = TO_EMAIL

    server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
    server.starttls()
    server.login(SMTP_USERNAME, SMTP_PASSWORD)
    server.sendmail(FROM_EMAIL, TO_EMAIL, message.as_string())
    server.quit()
